// <auto-generated />
using HeavenlyNightRecords.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeavenlyNightRecords.Migrations
{
    [DbContext(typeof(RecordDbContext))]
    [Migration("20241019065410_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HeavenlyNightRecords.Models.Records", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Record");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Awaken, My Love!",
                            Artist = "Childish Gambino",
                            Genre = "RnB",
                            Price = 20m,
                            year = 2016
                        },
                        new
                        {
                            Id = 2,
                            Album = "Songs in A Minor",
                            Artist = "Alicia Keys",
                            Genre = "RnB",
                            Price = 20m,
                            year = 2001
                        },
                        new
                        {
                            Id = 3,
                            Album = "Good Kid, M.A.A.D City",
                            Artist = "Kendrick Lamar",
                            Genre = "Rap",
                            Price = 20m,
                            year = 2011
                        },
                        new
                        {
                            Id = 4,
                            Album = "Operation: Doomsday",
                            Artist = "MF DOOM",
                            Genre = "Rap",
                            Price = 20m,
                            year = 1999
                        },
                        new
                        {
                            Id = 5,
                            Album = "Abbey Road",
                            Artist = "The Beatles",
                            Genre = "Rock",
                            Price = 20m,
                            year = 1969
                        },
                        new
                        {
                            Id = 6,
                            Album = "The Dark Side of the Moon",
                            Artist = "Pink Floyd",
                            Genre = "Rock",
                            Price = 20m,
                            year = 1973
                        },
                        new
                        {
                            Id = 7,
                            Album = "Seasons in the Abyss",
                            Artist = "Slayer",
                            Genre = "Metal",
                            Price = 20m,
                            year = 1990
                        },
                        new
                        {
                            Id = 8,
                            Album = "Blackbraid I",
                            Artist = "Blackbraid",
                            Genre = "Metal",
                            Price = 20m,
                            year = 2022
                        },
                        new
                        {
                            Id = 9,
                            Album = "Chet Baker Sings",
                            Artist = "Chet Baker",
                            Genre = "Jazz",
                            Price = 20m,
                            year = 1954
                        },
                        new
                        {
                            Id = 10,
                            Album = "The Duke Ellington & John Coltrane Album",
                            Artist = "Duke Ellington & John Coltrane",
                            Genre = "Jazz",
                            Price = 20m,
                            year = 1963
                        },
                        new
                        {
                            Id = 11,
                            Album = "Scenery",
                            Artist = "Ryo Fukui",
                            Genre = "Jazz",
                            Price = 20m,
                            year = 1976
                        },
                        new
                        {
                            Id = 12,
                            Album = "The Fame",
                            Artist = "Lady Gaga",
                            Genre = "Pop",
                            Price = 20m,
                            year = 2008
                        },
                        new
                        {
                            Id = 13,
                            Album = "Make It Big",
                            Artist = "Wham!",
                            Genre = "Pop",
                            Price = 20m,
                            year = 1984
                        },
                        new
                        {
                            Id = 14,
                            Album = "Traveller",
                            Artist = "Chris Stapleton",
                            Genre = "Country",
                            Price = 20m,
                            year = 2015
                        },
                        new
                        {
                            Id = 15,
                            Album = "Bitter Tears: Ballads of the American Indian",
                            Artist = "Johnny Cash",
                            Genre = "Country",
                            Price = 20m,
                            year = 1964
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
